### ISSUE TITLE
finding error thrown during cucumber execution

### ISSUE THREAD

**Issue by ssneha345** [cucumber/cucumber-java-skeleton#22] opened 2018-02-08 12:23 UTC
I am executing my cucumber feature file using  cucumber.api.cli.Main , execution is happening no issues with it. However i have a small requirement. Lets say my driver initialization fails in hooks because of some reason. I want to know that error after run. how can i get that error once the execution completes. and control comes out of "int exitstatus = run(options, Thread.currentThread().getContextClassLoader());" this line

```
import java.io.IOException;
import cucumber.api.cli.Main;
public class Execute extends Main{
public  static void runclimain()  {
    	String[] options = {"-g", "StepDfination","--plugin","/path/to/json/report.json", "-t", "<your tag    what you need to test", "/path/to/your/feature.feature"};

        try {
			int exitstatus = run(options, Thread.currentThread().getContextClassLoader());
			  System.out.println("exitstatus"+ exitstatus);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }
}
```

**Comment by mlvandijk** [comment] 2018-02-08 15:37
Hello ssneha345 and welcome!
For questions please one of the [support options](https://cucumber.io/support).
GitHub issues are used to report bugs or request features.

**Comment by mlvandijk** [comment] 2018-02-08 15:41
From the example provided, you have an interesting way of running Cucumber.
Common usage would be to run Cucumber from the command line, using class Main and providing the options as arguments.
Could you explain why you would only want to see the error only *after* the run? If your driver initialization fails (as per your example), wouldn't you want your test to fail right away?

**Comment by ssneha345** [comment] 2018-02-09 05:45
you are right..if there is some error say for driver initialization test should fail right away..which is happening..but i also want to know why the test fail , may be with the help of some exception thrown or just like in junit.result we have result.getFailures(), via which we can know the failure and its reason.

**Comment by ssneha345** [comment] 2018-02-09 11:39
if i can get the exception thrown from the cucumber code in the @After method of hooks. i think that will also satisfy my need.

**Comment by mlvandijk** [comment] 2018-02-09 12:53
@ssneha345 Ok, do I understand correctly that you want to know *why* it failed? 
Afaik I get a stack trace in my console when running tests locally and they fail. I'm running my test from a JUnit runner (like the RunCukesTest in this example project). Could you give that a try, please?

**Comment by aslakhellesoy** [comment] 2018-02-09 14:05
I'm closing this since it's a question and not a bug report or feature request.

**Closed by aslakhellesoy** 2018-02-09 14:05 UTC
Labels: question
